### ISSUE TITLE
Support Arabic Translation 

### ISSUE THREAD

**Issue by StephenVinuya** [asoftwareworld/ASW-Form-Builder-Pro#1]
Please implement the arabic translations provided below.

[ar 1.json](https://github.com/asoftwareworld/ASW-Form-Builder-Pro/files/12891451/ar.1.json)

**Comment by inglesachin99** [comment]
Hi Stephen,
Appreciate the translation file. We'll start integrating the Arabic translations and plan to deliver a new release promptly on Monday morning.

**Comment by asoftwareworld** [comment]
The translation for Arabic language has been included.
